import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices, type PartialLangiumSharedServices } from 'langium/lsp';
import { TorquescriptGeneratedModule, TorquescriptGeneratedSharedModule } from './generated/module.js';
import { TorquescriptCompletionProvider } from './torquescript-completion-provider.js';
import { TorquescriptDefinitionProvider } from './torquescript-definition-provider.js';
import { TorquescriptDocumentBuilder } from './torquescript-document-builder.js';
import { TorquescriptDocumentValidator } from './torquescript-document-validator.js';
import { TorquescriptHoverProvider } from './torquescript-hover-provider.js';
import { TorquescriptJsdocCodeActionProvider } from './torquescript-jsdoc-code-action-provider.js';
import { TorquescriptNodeKindProvider } from './torquescript-node-kind-provider.js';
import { TorquescriptScopeComputation, TorquescriptNameProvider } from './torquescript-scope.js';
import { TorquescriptScopeProvider } from './torquescript-scope-provider.js';
import { TorquescriptSignatureHelpProvider } from './torquescript-signature-help-provider.js';
import { TorquescriptValidator, registerValidationChecks } from './torquescript-validator.js';
import { TorquescriptWorkspaceManager } from './torquescript-workspace-manager.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TorquescriptAddedServices = {
    validation: {
        TorquescriptValidator: TorquescriptValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TorquescriptServices = LangiumServices & TorquescriptAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TorquescriptModule: Module<TorquescriptServices, PartialLangiumServices & TorquescriptAddedServices> = {
    references: {
        ScopeComputation: (services) => new TorquescriptScopeComputation(services),
        ScopeProvider: (services) => new TorquescriptScopeProvider(services),
        NameProvider: () => new TorquescriptNameProvider()
    },
    validation: {
        TorquescriptValidator: (services) => new TorquescriptValidator(services),
        DocumentValidator: (services) => new TorquescriptDocumentValidator(services)
    },
    lsp: {
        HoverProvider: (services) => new TorquescriptHoverProvider(services),
        DefinitionProvider: (services) => new TorquescriptDefinitionProvider(services),
        CompletionProvider: (services) => new TorquescriptCompletionProvider(services),
        SignatureHelp: () => new TorquescriptSignatureHelpProvider(),
        CodeActionProvider: (services) => new TorquescriptJsdocCodeActionProvider(services)
    }
};

/**
 * Shared module: overrides the WorkspaceManager so that a user-supplied console-API dump
 * (torquescript.config.json + the two dump files it points to) is loaded as a synthetic
 * document contributing built-in functions/classes to the global scope.
 */
export const TorquescriptSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    workspace: {
        WorkspaceManager: (services) => new TorquescriptWorkspaceManager(services),
        DocumentBuilder: (services) => new TorquescriptDocumentBuilder(services)
    },
    lsp: {
        NodeKindProvider: () => new TorquescriptNodeKindProvider()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTorquescriptServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Torquescript: TorquescriptServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        TorquescriptGeneratedSharedModule,
        TorquescriptSharedModule
    );
    const Torquescript = inject(
        createDefaultModule({ shared }),
        TorquescriptGeneratedModule,
        TorquescriptModule
    );
    shared.ServiceRegistry.register(Torquescript);
    registerValidationChecks(Torquescript);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Torquescript };
}
